"""Added UserPastEmail Table

Revision ID: 1c05ded6c1ec
Revises: 25e7a9839cd4
Create Date: 2013-09-06 16:00:01.495557

"""

# revision identifiers, used by Alembic.
revision = '1c05ded6c1ec'
down_revision = '25e7a9839cd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpastemail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userpastemail')
    ### end Alembic commands ###
