"""namespace column

Revision ID: 3b3583fcbaea
Revises: 7b0ba76b89e
Create Date: 2013-11-10 00:21:06.881127

"""

# revision identifiers, used by Alembic.
revision = '3b3583fcbaea'
down_revision = '7b0ba76b89e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import select, bindparam

from lastuser_core.models import Client
from coaster.utils import namespace_from_url


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('namespace', sa.String(length=250), nullable=True))
    op.create_unique_constraint('client_namespace_key', 'client', ['namespace'])
    ### end Alembic commands ###

    connection = op.get_bind()
    client = Client.__table__
    result = connection.execute(select([client.c.id, client.c.website]))
    namespaces = []
    namespace_list = []
    for r in result:
        new_namespace = namespace = namespace_from_url(r[1])
        append_count = 0
        while new_namespace in namespace_list:
            append_count = append_count + 1
            new_namespace = "%s_%s" % (namespace, append_count)
        namespaces.append(dict(clientid=r[0], namespace=new_namespace))
    updt_stmt = client.update().where(client.c.id == bindparam('clientid')).values(namespace=bindparam('namespace'))
    connection.execute(updt_stmt, namespaces)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'namespace')
    ### end Alembic commands ###
